import type { ClickUpTask } from "./clickup/types.js";

import { runClaude, runRalphLoop } from "./claude/runner.js";
import {
  addComment,
  updateTaskStatus,
} from "./clickup/client.js";
import { buildKickoffPrompt } from "./clickup/prompt-builder.js";
import { getConfig } from "./config.js";
import { insertRun, updateRun } from "./db.js";
import { cancelledRuns, emitSystemLine, taskEvents } from "./events.js";
import {
  commitAll,
  createBranch,
  ensureRepo,
  hasChanges,
  pushAndCreatePR,
  removeRalphScaffolding,
} from "./github/manager.js";
import { createChildLogger } from "./logger.js";

const log = createChildLogger("executor");

/**
 * Two-phase task execution:
 *
 * Phase 1 (Kickoff): Run Claude to read the ClickUp task and generate
 *   scripts/ralph/prd.json — breaking the task into ordered user stories.
 *
 * Phase 2 (Ralph Loop): Run ralph.sh which spawns fresh Claude instances
 *   per iteration, each implementing one story from prd.json until all pass.
 */
export async function executeTask(
  task: ClickUpTask,
  repoUrl: string,
): Promise<void> {
  const config = getConfig();
  const runId = insertRun(task.id, repoUrl);
  log.info(
    { runId, taskId: task.id, taskName: task.name },
    "Starting task execution",
  );

  try {
    // CLAIMED — Update ClickUp
    await updateTaskStatus(task.id, "in progress");
    await addComment(
      task.id,
      "🤖 Claude Task Runner has claimed this task and is starting work.",
    );

    // CLONING — Clone/pull repo and create branch
    emitSystemLine(runId, `Claiming task: ${task.name} (${task.id})`);
    updateRun(runId, { status: "cloning" });
    taskEvents.emit("status:changed", { runId, status: "cloning" });
    emitSystemLine(runId, `Cloning/fetching repo: ${repoUrl}`);
    const repoPath = await ensureRepo(repoUrl);
    const branchName = await createBranch(repoPath, task.id, task.name);
    updateRun(runId, { branch_name: branchName });

    if (cancelledRuns.has(runId)) {
      throw new Error("Task was cancelled");
    }

    emitSystemLine(runId, `Repo ready — branch: ${branchName}`);
    log.info({ branchName, repoPath }, "Repo ready");

    // PHASE 1: KICKOFF — Generate prd.json from ClickUp task
    updateRun(runId, { status: "running_claude" });
    taskEvents.emit("status:changed", { runId, status: "running_claude" });
    emitSystemLine(runId, "Phase 1: Running Claude kickoff to generate prd.json...");
    await addComment(
      task.id,
      "📋 Phase 1: Analyzing task and generating execution plan (prd.json)...",
    );

    const kickoffPrompt = buildKickoffPrompt(task, branchName);
    const kickoffResult = await runClaude(repoPath, kickoffPrompt, undefined, runId);

    if (kickoffResult.costUsd) {
      updateRun(runId, { cost_usd: kickoffResult.costUsd });
    }

    if (!kickoffResult.success) {
      throw new Error(
        `Kickoff phase failed — could not generate prd.json.\n\nOutput:\n${kickoffResult.output.slice(0, 3000)}`,
      );
    }

    emitSystemLine(runId, "Phase 1 complete — prd.json generated");
    log.info("Kickoff complete, prd.json generated");

    if (cancelledRuns.has(runId)) {
      throw new Error("Task was cancelled");
    }

    // PHASE 2: RALPH LOOP — Execute stories one at a time
    await addComment(
      task.id,
      "🔄 Phase 2: Running Ralph loop to implement stories...",
    );

    emitSystemLine(runId, `Phase 2: Starting Ralph loop (max ${String(config.CLAUDE_MAX_TURNS)} iterations)...`);
    const ralphResult = await runRalphLoop(repoPath, config.CLAUDE_MAX_TURNS, runId);

    if (!ralphResult.success) {
      throw new Error(
        `Ralph loop did not complete all stories.\n\nOutput:\n${ralphResult.output.slice(0, 3000)}`,
      );
    }

    emitSystemLine(runId, "Ralph loop complete — all stories passing");
    log.info("Ralph loop complete, all stories passing");

    // CREATING_PR — Push and create PR
    updateRun(runId, { status: "creating_pr" });
    taskEvents.emit("status:changed", { runId, status: "creating_pr" });
    emitSystemLine(runId, "Cleaning up scaffolding and pushing...");

    // Remove ralph scaffolding — it's task runner internals, not project code
    await removeRalphScaffolding(repoPath);

    if (await hasChanges(repoPath)) {
      await commitAll(repoPath, `chore: finalize ${task.name} (ClickUp #${task.id})`);
    }

    const prBody = [
      `## ClickUp Task`,
      `[${task.name}](${task.url})`,
      "",
      `## Summary`,
      `Automated implementation by Claude Task Runner using the Ralph loop.`,
      "",
      task.description
        ? `## Task Description\n${task.description.slice(0, 2000)}`
        : "",
      "",
      `---`,
      `🤖 Generated by Claude Task Runner`,
    ]
      .filter(Boolean)
      .join("\n");

    const prUrl = await pushAndCreatePR(
      repoPath,
      branchName,
      `feat: ${task.name}`,
      prBody,
    );

    // DONE — Update everything
    updateRun(runId, { pr_url: prUrl, status: "done" });
    taskEvents.emit("status:changed", { runId, status: "done" });

    await addComment(
      task.id,
      `✅ Claude Task Runner has completed this task!\n\nPR: ${prUrl}\n\nPlease review the changes.`,
    );
    await updateTaskStatus(task.id, "READY FOR PR");

    log.info({ prUrl, runId, taskId: task.id }, "Task completed successfully");
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log.error(
      { error: message, runId, taskId: task.id },
      "Task execution failed",
    );

    emitSystemLine(runId, `FAILED: ${message.slice(0, 500)}`);
    updateRun(runId, { error_message: message, status: "failed" });
    taskEvents.emit("status:changed", { runId, status: "failed" });
    cancelledRuns.delete(runId);

    try {
      await addComment(
        task.id,
        `❌ Claude Task Runner encountered an error:\n\n\`\`\`\n${message.slice(0, 2000)}\n\`\`\`\n\nPlease check the logs and try again.`,
      );
    } catch (commentErr) {
      log.error(commentErr, "Failed to post error comment to ClickUp");
    }
  }
}
